name: Linting & Testing
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Set up Go
        uses: useblacksmith/setup-go@v6
        with:
          go-version: 1.23
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: useblacksmith/golangci-lint-action@v6
        with:
          skip-go-installation: true
          args: --version
          version: v1.54
  tests:
    name: tests
    needs: lint
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Set up Go 1.23
        uses: useblacksmith/setup-go@v6
        with:
          go-version: "1.23"
        id: go
      - uses: actions/checkout@v4
      - uses: useblacksmith/cache@v5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - name: test
        run: |
          go test --cover ./... -v
